### ISSUE TITLE
customizable

### ISSUE THREAD

**Issue by YasinKalca18** [Vecnavium/LoadEveryWorlds#8]
add an option to load specific worlds.

**Comment by cosmicnebula200** [comment]
The plugin name is "LoadEveryWorld" it would not make sense if it only loaded specific worlds. ¯\_(ツ)_/¯

**Comment by JustJoostNL** [comment]
> add an option to load specific worlds.

You can use this one https://poggit.pmmp.io/p/LoadAllWorlds/
